name: Android Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    name: Build & Upload Release AAB
    runs-on: ubuntu-latest

    env:
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Decode Keystore
        run: |
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 -d > keystore.jks

      - name: Create local.properties
        run: |
          echo "signing.store.file=keystore.jks" >> local.properties
          echo "signing.store.password=$SIGNING_STORE_PASSWORD" >> local.properties
          echo "signing.key.alias=$SIGNING_KEY_ALIAS" >> local.properties
          echo "signing.key.password=$SIGNING_KEY_PASSWORD" >> local.properties

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      - name: Build Release AAB
        run: ./gradlew bundleRelease

      - name: Get AAB Path
        id: aab_path
        run: |
          AAB_PATH=$(find . -name "*release*.aab" | head -n 1)
          echo "aab_path=$AAB_PATH" >> $GITHUB_OUTPUT

      - name: Upload AAB to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: ${{ steps.aab_path.outputs.aab_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}